# Generated by Django 5.1.4 on 2025-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_info_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='text',
            field=models.TextField(default=1, verbose_name='Info text'),
            preserve_default=False,
        ),
    ]
