# Generated by Django 5.1.4 on 2025-03-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_af',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ar_dz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_be',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_bg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_bn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_bs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ckb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_cs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_cy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_da',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_dsb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_el',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en_au',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_eo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es_co',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es_mx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es_ni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es_ve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_et',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_eu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_gd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_gl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_he',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hsb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_io',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_kab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_km',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_kn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_lb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_lt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_lv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_mk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ml',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_mn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_mr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_my',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_nb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_nl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_nn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_pa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_pl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_pt_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sr_latn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_sw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_te',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_tg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_th',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_tk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_tt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_udm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_vi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_zh_hant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_af',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ar',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ar_dz',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ast',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_az',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_be',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_bg',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_bn',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_br',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_bs',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ca',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ckb',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_cs',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_cy',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_da',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_de',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_dsb',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_el',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en_au',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en_gb',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_eo',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es_ar',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es_co',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es_mx',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es_ni',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_es_ve',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_et',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_eu',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_fa',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_fi',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_fr',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_fy',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ga',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_gd',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_gl',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_he',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hi',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hr',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hsb',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hu',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hy',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ia',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ig',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ind',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_io',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_is',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_it',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ja',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ka',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_kab',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_kk',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_km',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_kn',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ko',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ky',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_lb',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_lt',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_lv',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_mk',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ml',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_mn',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_mr',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ms',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_my',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_nb',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ne',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_nl',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_nn',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_os',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_pa',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_pl',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_pt',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_pt_br',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ro',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sk',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sl',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sq',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sr',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sr_latn',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sv',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_sw',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ta',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_te',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tg',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_th',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tk',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tr',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tt',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_udm',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ug',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_uk',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ur',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_uz',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_vi',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_zh_hans',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_zh_hant',
            field=models.ManyToManyField(null=True, to='main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_af',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ast',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bg',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bs',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_cy',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_da',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_el',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_eo',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_et',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fy',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ga',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_gd',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hr',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hu',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ia',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ig',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_io',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_is',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kab',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_km',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kn',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_lb',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_lt',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_lv',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ml',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mn',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ms',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_my',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_nb',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_nn',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_os',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pa',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sk',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ta',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_te',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tk',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tt',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_udm',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ug',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ur',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_af',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ar',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ar_dz',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ast',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_az',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_be',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_bg',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_bn',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_br',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_bs',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ca',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ckb',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_cs',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_cy',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_da',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_de',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_dsb',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_el',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_en',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_en_au',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_en_gb',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_eo',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_es',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_es_ar',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_es_co',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_es_mx',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_es_ni',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_es_ve',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_et',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_eu',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_fa',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_fi',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_fr',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_fy',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ga',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_gd',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_gl',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_he',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_hi',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_hr',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_hsb',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_hu',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_hy',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ia',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ig',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ind',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_io',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_is',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_it',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ja',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ka',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_kab',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_kk',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_km',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_kn',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ko',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ky',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_lb',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_lt',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_lv',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_mk',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ml',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_mn',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_mr',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ms',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_my',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_nb',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ne',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_nl',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_nn',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_os',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_pa',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_pl',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_pt',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_pt_br',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ro',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ru',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sk',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sl',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sq',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sr',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sr_latn',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sv',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sw',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ta',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_te',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_tg',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_th',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_tk',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_tr',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_tt',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_udm',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ug',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_uk',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ur',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_uz',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_vi',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_zh_hans',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_zh_hant',
            field=models.ManyToManyField(null=True, to='main.size'),
        ),
    ]
