# Generated by Django 5.1.4 on 2025-03-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_product_category_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ru',
        ),
    ]
