# Generated by Django 5.1.4 on 2025-03-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_category_name_en_category_name_hy_category_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
    ]
