# Generated by Django 5.1.7 on 2025-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_ru',
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_hy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
